name: Test + Image + Deploy

on:
  push:
    paths-ignore:
      - 'swagger/**'
      - '**/README.md'
      - '**/.gitignore'
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_HOST: mysql
          MYSQL_DATABASE: trading
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Unit-Test
        env:
          DB_HOST: localhost:3306
          DB_PASSWORD: ''
          DB_NAME: trading
          DB_USER: root
        run: mvn test -Psurefire
  build-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build to GitHub Container Registry
        # use jib plugin to build docker image
        run: >
          mvn compile
          com.google.cloud.tools:jib-maven-plugin:3.1.4:build
          -Djib.to.image=ghcr.io/the-microservice-dungeon/trading/tradingservice
          -Djib.from.image=eclipse-temurin:17-alpine
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: stop-pull-run
        uses: appleboy/ssh-action@master
        env:
          SERVICE_NAME: trading
        with:
          host: cides03.gm.fh-koeln.de
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PWD }}
          port: 22
          envs: SERVICE_NAME
          script: |
            echo ${{ secrets.PROD_PWD }} | sudo -S docker-compose -f $SERVICE_NAME/service-compose.yml pull
            echo ${{ secrets.PROD_PWD }} | sudo -S docker-compose -f $SERVICE_NAME/service-compose.yml up -d
