name: CI Something Test

# Controls when the workflow will run
on:
  pull_request:
    paths-ignore:
      - 'swagger/**'
      - '**/README.md'
      - '**/.gitignore'
    branches:
      - 'main'
    types:
      [synchronize,opened]
  push:
    paths-ignore:
      - 'swagger/**'
      - '**/README.md'
      - '**/.gitignore'
    branches:
      - 'devops'
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_HOST: mysql
          MYSQL_DATABASE: trading
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Unit-Test
        env:
          DB_HOST: localhost:3306
          DB_PASSWORD: ''
          DB_NAME: trading
          DB_USER: root
        run: mvn test -Psurefire
        
