name: CI Unit Test

# Controls when the workflow will run
on:
  push:
    branches:
      - 'devops'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3606:3606
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup JDK 11 + cache
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          # setup maven cache as well
          cache: maven
      - name: Unit-Test
        run: mvn test